# Generated by Django 4.2.1 on 2023-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('subject', models.CharField(choices=[('MATH', 'Mathématiques'), ('PHYS', 'Physique'), ('CHIM', 'Chimie'), ('BIO', 'Biologie'), ('HIST', 'Histoire'), ('GEO', 'Géographie'), ('FR', 'Français'), ('ENG', 'Anglais'), ('PHILO', 'Philosophie'), ('ART', 'Arts'), ('MUS', 'Musique'), ('PE', 'Education Physique'), ('IT', 'Informatique'), ('ECO', 'Economie')], max_length=20, verbose_name='Subject')),
                ('coefficient', models.IntegerField(default=1, verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('level', models.CharField(choices=[('MAT1', 'Maternelle 1'), ('MAT2', 'Maternelle 2'), ('C1', 'Primaire C1'), ('CP', 'Primaire CP'), ('CE1', 'Primaire CE1'), ('CE2', 'Primaire CE2'), ('CM1', 'Primaire CM1'), ('CM2', 'Primaire CM2'), ('6EME', 'Secondaire 6eme'), ('5EME', 'Secondaire 5eme'), ('4EME', 'Secondaire 4eme'), ('3EME', 'Secondaire 3eme'), ('2ND', 'Secondaire 2nd'), ('1ERE', 'Secondaire 1ere'), ('TERM', 'Secondaire Terminal'), ('L1', 'Universitaire Licence 1'), ('L2', 'Universitaire Licence 2'), ('L3', 'Universitaire Licence 3'), ('M1', 'Universitaire Master 1'), ('M2', 'Universitaire Master 2'), ('PHD', 'Doctorat')], max_length=30, verbose_name='Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
