# Generated by Django 4.2.1 on 2023-06-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etabs', '0003_alter_establishment_head'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'schoolclass')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'establishment')},
        ),
    ]
