# Generated by Django 4.2.1 on 2023-05-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_Establishments', to=settings.AUTH_USER_MODEL, verbose_name='User who created'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name__icontains': 'HEAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_establishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishment',
            name='types',
            field=models.ManyToManyField(to='etabs.establishmenttype', verbose_name='Types'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_Establishments', to=settings.AUTH_USER_MODEL, verbose_name='User who updated'),
        ),
    ]
