# Generated by Django 4.2.1 on 2023-06-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etabs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name__icontains': 'Head'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_establishments', to=settings.AUTH_USER_MODEL),
        ),
    ]
