# Generated by Django 4.2.1 on 2023-06-02 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etabs', '0001_initial'),
        ('classes', '0001_initial'),
        ('calendrier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeslots', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendrier.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='schoolclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_timeslots', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='room',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etabs.establishment', verbose_name='Establishment'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('room', 'start_datetime', 'end_datetime')},
        ),
    ]
