# Generated by Django 4.2.1 on 2023-07-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'capacity')},
        ),
    ]
