# Generated by Django 4.2.1 on 2023-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='CommunicationBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Homework')),
                ('parent_seen', models.BooleanField(default=False, verbose_name='Parent has seen')),
                ('parent_acknowledged', models.BooleanField(default=False, verbose_name='Parent has acknowledged')),
            ],
            options={
                'verbose_name': 'Communication Book',
                'verbose_name_plural': 'Communication Books',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='communicationbook_photos/')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
