# Generated by Django 4.2.1 on 2023-06-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suivi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('roles__name', 'Student')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='communicationbook',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('roles__name', 'Student')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communicationbook_entries', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
